using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Massage functionality
public class MassageWork : MonoBehaviour
{
    private float timer = 0f;
    private GameObject person;
    private GameObject puppy;

    private bool isPerson = false;
    private bool isPuppy = false;
    private bool newCustomer = true;
    private bool changeMove = false;

    void Update() {
        // If puppy and person is there
        if(isPerson && isPuppy && newCustomer && puppy) {
            // If the puppy is not currently leaving and it hasn't been served yet, prevent them from moving,
            // pause happiness degradation, and alter attributes
            if(!puppy.GetComponent<PuppyCustomer>().puppyLeaving() && !changeMove) {
                person.GetComponent<PlayerClickToMove>().setMove();
                puppy.GetComponent<PuppyDragAndDrop>().setMove();
                puppy.GetComponent<PuppyCustomer>().pauseHappiness();
                puppy.GetComponent<PuppyCustomer>().destroyThought();
                puppy.GetComponent<PuppyCustomer>().instantiateCloud();
                changeMove = true;
            }
            // After 3 seconds, allow them to leave, unpause happiness, destroy the attribute and alert the puppy
            timer += (Time.deltaTime)%60;
            if(timer >= 6) {
                newCustomer = false;
                person.GetComponent<PlayerClickToMove>().setMove();
                puppy.GetComponent<PuppyDragAndDrop>().setMove();
                puppy.GetComponent<PuppyCustomer>().pauseHappiness();
                puppy.GetComponent<PuppyCustomer>().destroyCloud();
                puppy.GetComponent<PuppyCustomer>().removeStation(3);
                timer = 0f;
            }
        }
    }

    // Setter functions
    public void send(GameObject p) {
        if(p.tag == "Puppy") {
            newCustomer = true;
            changeMove = false;
            puppy = p;
            isPuppy = true;
        }
        else {
            person = p;
            isPerson = true;
        }
    }

    public void remove(GameObject p) {
        if(p.tag == "Puppy") {
            puppy = null;
            isPuppy = false;
        }
        else {
            person = null;
            isPerson = false;
        }
    }
}
